# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Hosted Ubuntu 1604

steps:

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Cloud Console Development (ae43b1e3-c35d-4c8c-bc0d-f148b4c52b78)'
    dockerFile: Dockerfile
    imageName: 'virtual-kubelet-aci:$(Build.SourceBranchName)_$(Build.BuildNumber)'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Cloud Console Development (ae43b1e3-c35d-4c8c-bc0d-f148b4c52b78)'
    azureContainerRegistry: '{"loginServer":"vkaci.azurecr.io", "id" : "/subscriptions/ae43b1e3-c35d-4c8c-bc0d-f148b4c52b78/resourceGroups/virtual-kubelet/providers/Microsoft.ContainerRegistry/registries/vkaci"}'
    action: 'Push an image'
    imageName: 'virtual-kubelet-aci:$(Build.SourceBranchName)_$(Build.BuildNumber)'
