apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vk.fullname" . }}-{{ .Values.image.secretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
