version: 2
jobs:
  validate:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/virtual-kubelet/virtual-kubelet
    steps:
      - checkout
      - run:
          name: go vet
          command: make vet
      - run:
          name: Install linters
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s v1.15.0
      - run:
          name: Lint
          command: make LINTER_BIN="./bin/golangci-lint" lint
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/virtual-kubelet/azure-aci
    steps:
      - checkout
      - run:
        command: sh hack/ci/create_credentials.sh
      - run: |
          echo 'export AZURE_AUTH_LOCATION=${outputPathCredsfile}' >> $BASH_ENV
      - run:
        name: Tests
        command: go test -v $(go list ./...)

workflows:
  version: 2
  validate_and_test:
    jobs:
      - validate
      - test
